# Shell variables
# Generated by 'wal'
wallpaper="/home/baiken80/wallpaper/wallpaper/68340.jpg"

# Special
background='#0c0702'
foreground='#cce2db'
cursor='#cce2db'

# Colors
color0='#0c0702'
color1='#9F5E2A'
color2='#A6723D'
color3='#4C807D'
color4='#B38E56'
color5='#DDA057'
color6='#50BAC8'
color7='#cce2db'
color8='#8e9e99'
color9='#9F5E2A'
color10='#A6723D'
color11='#4C807D'
color12='#B38E56'
color13='#DDA057'
color14='#50BAC8'
color15='#cce2db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
