--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baiken80/wallpaper/wallpaper/103.jpg"

-- Special
background="#0E1D20"
foreground="#dcdacf"
cursor="#dcdacf"

-- Colors
color0="#0E1D20"
color1="#8E745A"
color2="#668670"
color3="#9F956A"
color4="#2A7D82"
color5="#59958E"
color6="#9FAA9A"
color7="#dcdacf"
color8="#9a9890"
color9="#8E745A"
color10="#668670"
color11="#9F956A"
color12="#2A7D82"
color13="#59958E"
color14="#9FAA9A"
color15="#dcdacf"
