--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baiken80/wallpaper/wallpaper/0qwp85.jpg"

-- Special
background="#020102"
foreground="#bfbfbf"
cursor="#bfbfbf"

-- Colors
color0="#020102"
color1="#D69370"
color2="#C27D81"
color3="#ABA992"
color4="#DBAF96"
color5="#BFC2AB"
color6="#DFCBB3"
color7="#bfbfbf"
color8="#414041"
color9="#D69370"
color10="#C27D81"
color11="#ABA992"
color12="#DBAF96"
color13="#BFC2AB"
color14="#DFCBB3"
color15="#bfbfbf"
