# Shell variables
# Generated by 'wal'
wallpaper="/home/baiken80/wallpaper/wallpaper/103.jpg"

# Special
background='#0E1D20'
foreground='#dcdacf'
cursor='#dcdacf'

# Colors
color0='#0E1D20'
color1='#8E745A'
color2='#668670'
color3='#9F956A'
color4='#2A7D82'
color5='#59958E'
color6='#9FAA9A'
color7='#dcdacf'
color8='#9a9890'
color9='#8E745A'
color10='#668670'
color11='#9F956A'
color12='#2A7D82'
color13='#59958E'
color14='#9FAA9A'
color15='#dcdacf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
